namespace Espmon;

// Generated Color Item Struct
public struct ColorItem
{
    public ColorItem(string name, string displayName, int value)
    {
        Name = name;
        DisplayName = displayName;
        Value = value;
    }

    public string Name { get; }
    public string DisplayName { get; }
    public int Value { get; }

    public static ColorItem[] AllColors { get; } = new ColorItem[]
    {
        new ColorItem("AliceBlue", "Alice blue", unchecked((int)0xFFF0F8FF)),
        new ColorItem("AntiqueWhite", "Antique white", unchecked((int)0xFFFAEBD7)),
        new ColorItem("Aqua", "Aqua", unchecked((int)0xFF00FFFF)),
        new ColorItem("Aquamarine", "Aquamarine", unchecked((int)0xFF7FFFD4)),
        new ColorItem("Azure", "Azure", unchecked((int)0xFFF0FFFF)),
        new ColorItem("Beige", "Beige", unchecked((int)0xFFF5F5DC)),
        new ColorItem("Bisque", "Bisque", unchecked((int)0xFFFFE4C4)),
        new ColorItem("Black", "Black", unchecked((int)0xFF000000)),
        new ColorItem("BlanchedAlmond", "Blanched almond", unchecked((int)0xFFFFEBCD)),
        new ColorItem("Blue", "Blue", unchecked((int)0xFF0000FF)),
        new ColorItem("BlueViolet", "Blue violet", unchecked((int)0xFF8A2BE2)),
        new ColorItem("Brown", "Brown", unchecked((int)0xFFA52A2A)),
        new ColorItem("BurlyWood", "Burly wood", unchecked((int)0xFFDEB887)),
        new ColorItem("CadetBlue", "Cadet blue", unchecked((int)0xFF5F9EA0)),
        new ColorItem("Chartreuse", "Chartreuse", unchecked((int)0xFF7FFF00)),
        new ColorItem("Chocolate", "Chocolate", unchecked((int)0xFFD2691E)),
        new ColorItem("Coral", "Coral", unchecked((int)0xFFFF7F50)),
        new ColorItem("CornflowerBlue", "Cornflower blue", unchecked((int)0xFF6495ED)),
        new ColorItem("Cornsilk", "Cornsilk", unchecked((int)0xFFFFF8DC)),
        new ColorItem("Crimson", "Crimson", unchecked((int)0xFFDC143C)),
        new ColorItem("Cyan", "Cyan", unchecked((int)0xFF00FFFF)),
        new ColorItem("DarkBlue", "Dark blue", unchecked((int)0xFF00008B)),
        new ColorItem("DarkCyan", "Dark cyan", unchecked((int)0xFF008B8B)),
        new ColorItem("DarkGoldenrod", "Dark goldenrod", unchecked((int)0xFFB8860B)),
        new ColorItem("DarkGray", "Dark gray", unchecked((int)0xFFA9A9A9)),
        new ColorItem("DarkGreen", "Dark green", unchecked((int)0xFF006400)),
        new ColorItem("DarkKhaki", "Dark khaki", unchecked((int)0xFFBDB76B)),
        new ColorItem("DarkMagenta", "Dark magenta", unchecked((int)0xFF8B008B)),
        new ColorItem("DarkOliveGreen", "Dark olive green", unchecked((int)0xFF556B2F)),
        new ColorItem("DarkOrange", "Dark orange", unchecked((int)0xFFFF8C00)),
        new ColorItem("DarkOrchid", "Dark orchid", unchecked((int)0xFF9932CC)),
        new ColorItem("DarkRed", "Dark red", unchecked((int)0xFF8B0000)),
        new ColorItem("DarkSalmon", "Dark salmon", unchecked((int)0xFFE9967A)),
        new ColorItem("DarkSeaGreen", "Dark sea green", unchecked((int)0xFF8FBC8F)),
        new ColorItem("DarkSlateBlue", "Dark slate blue", unchecked((int)0xFF483D8B)),
        new ColorItem("DarkSlateGray", "Dark slate gray", unchecked((int)0xFF2F4F4F)),
        new ColorItem("DarkTurquoise", "Dark turquoise", unchecked((int)0xFF00CED1)),
        new ColorItem("DarkViolet", "Dark violet", unchecked((int)0xFF9400D3)),
        new ColorItem("DeepPink", "Deep pink", unchecked((int)0xFFFF1493)),
        new ColorItem("DeepSkyBlue", "Deep sky blue", unchecked((int)0xFF00BFFF)),
        new ColorItem("DimGray", "Dim gray", unchecked((int)0xFF696969)),
        new ColorItem("DodgerBlue", "Dodger blue", unchecked((int)0xFF1E90FF)),
        new ColorItem("Firebrick", "Firebrick", unchecked((int)0xFFB22222)),
        new ColorItem("FloralWhite", "Floral white", unchecked((int)0xFFFFFAF0)),
        new ColorItem("ForestGreen", "Forest green", unchecked((int)0xFF228B22)),
        new ColorItem("Fuchsia", "Fuchsia", unchecked((int)0xFFFF00FF)),
        new ColorItem("Gainsboro", "Gainsboro", unchecked((int)0xFFDCDCDC)),
        new ColorItem("GhostWhite", "Ghost white", unchecked((int)0xFFF8F8FF)),
        new ColorItem("Gold", "Gold", unchecked((int)0xFFFFD700)),
        new ColorItem("Goldenrod", "Goldenrod", unchecked((int)0xFFDAA520)),
        new ColorItem("Gray", "Gray", unchecked((int)0xFF808080)),
        new ColorItem("Green", "Green", unchecked((int)0xFF008000)),
        new ColorItem("GreenYellow", "Green yellow", unchecked((int)0xFFADFF2F)),
        new ColorItem("Honeydew", "Honeydew", unchecked((int)0xFFF0FFF0)),
        new ColorItem("HotPink", "Hot pink", unchecked((int)0xFFFF69B4)),
        new ColorItem("IndianRed", "Indian red", unchecked((int)0xFFCD5C5C)),
        new ColorItem("Indigo", "Indigo", unchecked((int)0xFF4B0082)),
        new ColorItem("Ivory", "Ivory", unchecked((int)0xFFFFFFF0)),
        new ColorItem("Khaki", "Khaki", unchecked((int)0xFFF0E68C)),
        new ColorItem("Lavender", "Lavender", unchecked((int)0xFFE6E6FA)),
        new ColorItem("LavenderBlush", "Lavender blush", unchecked((int)0xFFFFF0F5)),
        new ColorItem("LawnGreen", "Lawn green", unchecked((int)0xFF7CFC00)),
        new ColorItem("LemonChiffon", "Lemon chiffon", unchecked((int)0xFFFFFACD)),
        new ColorItem("LightBlue", "Light blue", unchecked((int)0xFFADD8E6)),
        new ColorItem("LightCoral", "Light coral", unchecked((int)0xFFF08080)),
        new ColorItem("LightCyan", "Light cyan", unchecked((int)0xFFE0FFFF)),
        new ColorItem("LightGoldenrodYellow", "Light goldenrod yellow", unchecked((int)0xFFFAFAD2)),
        new ColorItem("LightGray", "Light gray", unchecked((int)0xFFD3D3D3)),
        new ColorItem("LightGreen", "Light green", unchecked((int)0xFF90EE90)),
        new ColorItem("LightPink", "Light pink", unchecked((int)0xFFFFB6C1)),
        new ColorItem("LightSalmon", "Light salmon", unchecked((int)0xFFFFA07A)),
        new ColorItem("LightSeaGreen", "Light sea green", unchecked((int)0xFF20B2AA)),
        new ColorItem("LightSkyBlue", "Light sky blue", unchecked((int)0xFF87CEFA)),
        new ColorItem("LightSlateGray", "Light slate gray", unchecked((int)0xFF778899)),
        new ColorItem("LightSteelBlue", "Light steel blue", unchecked((int)0xFFB0C4DE)),
        new ColorItem("LightYellow", "Light yellow", unchecked((int)0xFFFFFFE0)),
        new ColorItem("Lime", "Lime", unchecked((int)0xFF00FF00)),
        new ColorItem("LimeGreen", "Lime green", unchecked((int)0xFF32CD32)),
        new ColorItem("Linen", "Linen", unchecked((int)0xFFFAF0E6)),
        new ColorItem("Magenta", "Magenta", unchecked((int)0xFFFF00FF)),
        new ColorItem("Maroon", "Maroon", unchecked((int)0xFF800000)),
        new ColorItem("MediumAquamarine", "Medium aquamarine", unchecked((int)0xFF66CDAA)),
        new ColorItem("MediumBlue", "Medium blue", unchecked((int)0xFF0000CD)),
        new ColorItem("MediumOrchid", "Medium orchid", unchecked((int)0xFFBA55D3)),
        new ColorItem("MediumPurple", "Medium purple", unchecked((int)0xFF9370DB)),
        new ColorItem("MediumSeaGreen", "Medium sea green", unchecked((int)0xFF3CB371)),
        new ColorItem("MediumSlateBlue", "Medium slate blue", unchecked((int)0xFF7B68EE)),
        new ColorItem("MediumSpringGreen", "Medium spring green", unchecked((int)0xFF00FA9A)),
        new ColorItem("MediumTurquoise", "Medium turquoise", unchecked((int)0xFF48D1CC)),
        new ColorItem("MediumVioletRed", "Medium violet red", unchecked((int)0xFFC71585)),
        new ColorItem("MidnightBlue", "Midnight blue", unchecked((int)0xFF191970)),
        new ColorItem("MintCream", "Mint cream", unchecked((int)0xFFF5FFFA)),
        new ColorItem("MistyRose", "Misty rose", unchecked((int)0xFFFFE4E1)),
        new ColorItem("Moccasin", "Moccasin", unchecked((int)0xFFFFE4B5)),
        new ColorItem("NavajoWhite", "Navajo white", unchecked((int)0xFFFFDEAD)),
        new ColorItem("Navy", "Navy", unchecked((int)0xFF000080)),
        new ColorItem("OldLace", "Old lace", unchecked((int)0xFFFDF5E6)),
        new ColorItem("Olive", "Olive", unchecked((int)0xFF808000)),
        new ColorItem("OliveDrab", "Olive drab", unchecked((int)0xFF6B8E23)),
        new ColorItem("Orange", "Orange", unchecked((int)0xFFFFA500)),
        new ColorItem("OrangeRed", "Orange red", unchecked((int)0xFFFF4500)),
        new ColorItem("Orchid", "Orchid", unchecked((int)0xFFDA70D6)),
        new ColorItem("PaleGoldenrod", "Pale goldenrod", unchecked((int)0xFFEEE8AA)),
        new ColorItem("PaleGreen", "Pale green", unchecked((int)0xFF98FB98)),
        new ColorItem("PaleTurquoise", "Pale turquoise", unchecked((int)0xFFAFEEEE)),
        new ColorItem("PaleVioletRed", "Pale violet red", unchecked((int)0xFFDB7093)),
        new ColorItem("PapayaWhip", "Papaya whip", unchecked((int)0xFFFFEFD5)),
        new ColorItem("PeachPuff", "Peach puff", unchecked((int)0xFFFFDAB9)),
        new ColorItem("Peru", "Peru", unchecked((int)0xFFCD853F)),
        new ColorItem("Pink", "Pink", unchecked((int)0xFFFFC0CB)),
        new ColorItem("Plum", "Plum", unchecked((int)0xFFDDA0DD)),
        new ColorItem("PowderBlue", "Powder blue", unchecked((int)0xFFB0E0E6)),
        new ColorItem("Purple", "Purple", unchecked((int)0xFF800080)),
        new ColorItem("RebeccaPurple", "Rebecca purple", unchecked((int)0xFF663399)),
        new ColorItem("Red", "Red", unchecked((int)0xFFFF0000)),
        new ColorItem("RosyBrown", "Rosy brown", unchecked((int)0xFFBC8F8F)),
        new ColorItem("RoyalBlue", "Royal blue", unchecked((int)0xFF4169E1)),
        new ColorItem("SaddleBrown", "Saddle brown", unchecked((int)0xFF8B4513)),
        new ColorItem("Salmon", "Salmon", unchecked((int)0xFFFA8072)),
        new ColorItem("SandyBrown", "Sandy brown", unchecked((int)0xFFF4A460)),
        new ColorItem("SeaGreen", "Sea green", unchecked((int)0xFF2E8B57)),
        new ColorItem("SeaShell", "Sea shell", unchecked((int)0xFFFFF5EE)),
        new ColorItem("Sienna", "Sienna", unchecked((int)0xFFA0522D)),
        new ColorItem("Silver", "Silver", unchecked((int)0xFFC0C0C0)),
        new ColorItem("SkyBlue", "Sky blue", unchecked((int)0xFF87CEEB)),
        new ColorItem("SlateBlue", "Slate blue", unchecked((int)0xFF6A5ACD)),
        new ColorItem("SlateGray", "Slate gray", unchecked((int)0xFF708090)),
        new ColorItem("Snow", "Snow", unchecked((int)0xFFFFFAFA)),
        new ColorItem("SpringGreen", "Spring green", unchecked((int)0xFF00FF7F)),
        new ColorItem("SteelBlue", "Steel blue", unchecked((int)0xFF4682B4)),
        new ColorItem("Tan", "Tan", unchecked((int)0xFFD2B48C)),
        new ColorItem("Teal", "Teal", unchecked((int)0xFF008080)),
        new ColorItem("Thistle", "Thistle", unchecked((int)0xFFD8BFD8)),
        new ColorItem("Tomato", "Tomato", unchecked((int)0xFFFF6347)),
        new ColorItem("Transparent", "Transparent", unchecked((int)0x00FFFFFF)),
        new ColorItem("Turquoise", "Turquoise", unchecked((int)0xFF40E0D0)),
        new ColorItem("Violet", "Violet", unchecked((int)0xFFEE82EE)),
        new ColorItem("Wheat", "Wheat", unchecked((int)0xFFF5DEB3)),
        new ColorItem("White", "White", unchecked((int)0xFFFFFFFF)),
        new ColorItem("WhiteSmoke", "White smoke", unchecked((int)0xFFF5F5F5)),
        new ColorItem("Yellow", "Yellow", unchecked((int)0xFFFFFF00)),
        new ColorItem("YellowGreen", "Yellow green", unchecked((int)0xFF9ACD32)),
    };
}
