// <auto-generated>
//   Generated by build_all.ps1 -- do not edit by hand.
// </auto-generated>
#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
#define FIRMWARE_BOARD_ID 4
#define FIRMWARE_DISPLAY_NAME "Cheap Yellow Display 2432S028"
#define FIRMWARE_SLUG "cyd-2432S028"
#define LCD_INCHES ((float)2.8)
#endif
