// <auto-generated>
//   Generated by build_all.ps1 -- do not edit by hand.
// </auto-generated>
#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
#define FIRMWARE_BOARD_ID 6
#define FIRMWARE_DISPLAY_NAME "M5 Stack Core2"
#define FIRMWARE_SLUG "m5stack-core2"
#define LCD_INCHES ((float)2.0)
#endif
