// <auto-generated>
//   Generated by build_all.ps1 -- do not edit by hand.
// </auto-generated>
#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
#define FIRMWARE_BOARD_ID 1
#define FIRMWARE_DISPLAY_NAME "Matouch ESP32-S3 Parallel 3.5\""
#define FIRMWARE_SLUG "matouch-parallel-35"
#define LCD_INCHES ((float)3.5)
#endif
