// <auto-generated />
// Auto-generated by buffers_gen_cs_inline.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Htcw;

namespace Espmon.Elevation;

public enum ElevatedCommand : byte
{
    InstallService = 1,
    UninstallService = 2,
    InstalledCheck = 3,
    StartService = 4,
    StopService = 5,
    StartedCheck = 6,
    Shutdown = 7,
}

[InlineArray(256)]
struct InterfaceInlineCharLength256
{
    private char _e0;
}

public struct InterfaceMaxSize
{
    public const int Value = 519;
}

[StructLayout(LayoutKind.Auto)]
public partial struct InstalledCheck
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out InstalledCheck result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out InstalledCheck result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out InstalledCheck result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct StartedCheck
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out StartedCheck result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out StartedCheck result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out StartedCheck result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct InstallRequest
{
    public const int StructMaxSize = 514;

    private InterfaceInlineCharLength256 _FromAppPath;
    public string FromAppPath
    {
        get => new string(Buffers.TrimNullUtf16((ReadOnlySpan<char>)_FromAppPath));
        set { ReadOnlySpan<char> _v = value.AsSpan(); int _n = Math.Min(_v.Length, 256); _v.Slice(0, _n).CopyTo(((Span<char>)_FromAppPath)); if (_n < 256) ((Span<char>)_FromAppPath).Slice(_n).Clear(); }
    }
    [UnscopedRef] public ReadOnlySpan<char> GetFromAppPathSpan() => Buffers.TrimNullUtf16((ReadOnlySpan<char>)_FromAppPath);

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 2 + Buffers.TrimNullUtf16((ReadOnlySpan<char>)_FromAppPath).Length * 2;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out InstallRequest result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        {
            if (span.Length - offset < 2) { bytesRead = 0; return false; }
            int _l = (int)(BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset))); offset += 2;
            if (_l > 256 || span.Length - offset < _l * 2) { bytesRead = 0; return false; }
            for (int i = 0; i < _l; i++) { result._FromAppPath[i] = (char)(BinaryPrimitives.ReadInt16LittleEndian(span.Slice(offset))); offset += 2; }
            ((Span<char>)result._FromAppPath).Slice(_l).Clear();
        }
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        {
            int _l = Buffers.TrimNullUtf16((ReadOnlySpan<char>)_FromAppPath).Length;
            if (span.Length - offset < 2 + _l * 2) { bytesWritten = 0; return false; }
            BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), (ushort)_l); offset += 2;
            for (int i = 0; i < _l; i++) { BinaryPrimitives.WriteInt16LittleEndian(span.Slice(offset), (short)((ReadOnlySpan<char>)_FromAppPath)[i]); offset += 2; }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out InstallRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out InstallRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct RequestResponse
{
    public const int StructMaxSize = 519;

    private byte _Succeeded;
    public bool Succeeded { get => _Succeeded != 0; set => _Succeeded = value ? (byte)1 : (byte)0; }
    public uint ErrorCode;
    private InterfaceInlineCharLength256 _Message;
    public string Message
    {
        get => new string(Buffers.TrimNullUtf16((ReadOnlySpan<char>)_Message));
        set { ReadOnlySpan<char> _v = value.AsSpan(); int _n = Math.Min(_v.Length, 256); _v.Slice(0, _n).CopyTo(((Span<char>)_Message)); if (_n < 256) ((Span<char>)_Message).Slice(_n).Clear(); }
    }
    [UnscopedRef] public ReadOnlySpan<char> GetMessageSpan() => Buffers.TrimNullUtf16((ReadOnlySpan<char>)_Message);

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 4;
            size += 2 + Buffers.TrimNullUtf16((ReadOnlySpan<char>)_Message).Length * 2;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out RequestResponse result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result._Succeeded = (byte)(span[offset]);
        offset += 1;
        if (span.Length - offset < 4) { bytesRead = 0; return false; }
        result.ErrorCode = BinaryPrimitives.ReadUInt32LittleEndian(span.Slice(offset));
        offset += 4;
        {
            if (span.Length - offset < 2) { bytesRead = 0; return false; }
            int _l = (int)(BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset))); offset += 2;
            if (_l > 256 || span.Length - offset < _l * 2) { bytesRead = 0; return false; }
            for (int i = 0; i < _l; i++) { result._Message[i] = (char)(BinaryPrimitives.ReadInt16LittleEndian(span.Slice(offset))); offset += 2; }
            ((Span<char>)result._Message).Slice(_l).Clear();
        }
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = _Succeeded; offset += 1;
        if (span.Length - offset < 4) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteUInt32LittleEndian(span.Slice(offset), ErrorCode); offset += 4;
        {
            int _l = Buffers.TrimNullUtf16((ReadOnlySpan<char>)_Message).Length;
            if (span.Length - offset < 2 + _l * 2) { bytesWritten = 0; return false; }
            BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), (ushort)_l); offset += 2;
            for (int i = 0; i < _l; i++) { BinaryPrimitives.WriteInt16LittleEndian(span.Slice(offset), (short)((ReadOnlySpan<char>)_Message)[i]); offset += 2; }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out RequestResponse result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out RequestResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct UninstallRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out UninstallRequest result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out UninstallRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out UninstallRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct StartRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out StartRequest result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out StartRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out StartRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct StopRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out StopRequest result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out StopRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out StopRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct ShutdownRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ShutdownRequest result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ShutdownRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out ShutdownRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

#nullable restore