// <auto-generated />
// Auto-generated by buffers_gen_cs.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Htcw;

namespace Espmon.Elevation;

public enum ElevatedCommand : byte
{
    InstallService = 1,
    UninstallService = 2,
    InstalledCheck = 3,
    StartService = 4,
    StopService = 5,
    StartedCheck = 6,
    Shutdown = 7,
}

public struct InterfaceMaxSize
{
    public const int Value = 519;
}

public partial class InstalledCheck
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out InstalledCheck result, out int bytesRead)
    {
        result = new InstalledCheck();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out InstalledCheck result, out int bytesRead)
    {
        result = new InstalledCheck();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class StartedCheck
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out StartedCheck result, out int bytesRead)
    {
        result = new StartedCheck();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out StartedCheck result, out int bytesRead)
    {
        result = new StartedCheck();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class InstallRequest
{
    public const int StructMaxSize = 514;

    public string FromAppPath { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 2 + (string.IsNullOrEmpty(FromAppPath) ? 0 : Math.Min(FromAppPath.Length, 256) * 2);
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out InstallRequest result, out int bytesRead)
    {
        bytesRead = 0;
        result = new InstallRequest();
        int offset = 0;
        if (span.Length - offset < 2) return false;
        {
            int _len_FromAppPath = (int)(BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset)));
            offset += 2;
            int _byteLen_FromAppPath = _len_FromAppPath * 2;
            if (_len_FromAppPath > 256 || span.Length - offset < _byteLen_FromAppPath) return false;
            result.FromAppPath = Encoding.Unicode.GetString(span.Slice(offset, _byteLen_FromAppPath));
            offset += _byteLen_FromAppPath;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _charLen_FromAppPath = string.IsNullOrEmpty(FromAppPath) ? 0 : Math.Min(FromAppPath.Length, 256);
            int _byteLen_FromAppPath = _charLen_FromAppPath * 2;
            if (span.Length - offset < 2 + _byteLen_FromAppPath) return false;
            BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), (ushort)_charLen_FromAppPath);
            offset += 2;
            if (_byteLen_FromAppPath > 0)
            {
                Encoding.Unicode.GetBytes(FromAppPath.AsSpan(0, _charLen_FromAppPath), span.Slice(offset, _byteLen_FromAppPath));
                offset += _byteLen_FromAppPath;
            }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out InstallRequest result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out InstallRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[514];
        int n = stream.Read(buf);
        if (n < 514) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[514];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class RequestResponse
{
    public const int StructMaxSize = 519;

    public bool Succeeded { get; set; }
    public uint ErrorCode { get; set; }
    public string Message { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 4;
            size += 2 + (string.IsNullOrEmpty(Message) ? 0 : Math.Min(Message.Length, 256) * 2);
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out RequestResponse result, out int bytesRead)
    {
        bytesRead = 0;
        result = new RequestResponse();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.Succeeded = span[offset] != 0;
        offset += 1;
        if (span.Length - offset < 4) return false;
        result.ErrorCode = BinaryPrimitives.ReadUInt32LittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 2) return false;
        {
            int _len_Message = (int)(BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset)));
            offset += 2;
            int _byteLen_Message = _len_Message * 2;
            if (_len_Message > 256 || span.Length - offset < _byteLen_Message) return false;
            result.Message = Encoding.Unicode.GetString(span.Slice(offset, _byteLen_Message));
            offset += _byteLen_Message;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)(Succeeded ? 1 : 0);
        offset += 1;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteUInt32LittleEndian(span.Slice(offset), ErrorCode);
        offset += 4;
        {
            int _charLen_Message = string.IsNullOrEmpty(Message) ? 0 : Math.Min(Message.Length, 256);
            int _byteLen_Message = _charLen_Message * 2;
            if (span.Length - offset < 2 + _byteLen_Message) return false;
            BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), (ushort)_charLen_Message);
            offset += 2;
            if (_byteLen_Message > 0)
            {
                Encoding.Unicode.GetBytes(Message.AsSpan(0, _charLen_Message), span.Slice(offset, _byteLen_Message));
                offset += _byteLen_Message;
            }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out RequestResponse result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out RequestResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[519];
        int n = stream.Read(buf);
        if (n < 519) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[519];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class UninstallRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out UninstallRequest result, out int bytesRead)
    {
        result = new UninstallRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out UninstallRequest result, out int bytesRead)
    {
        result = new UninstallRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class StartRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out StartRequest result, out int bytesRead)
    {
        result = new StartRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out StartRequest result, out int bytesRead)
    {
        result = new StartRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class StopRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out StopRequest result, out int bytesRead)
    {
        result = new StopRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out StopRequest result, out int bytesRead)
    {
        result = new StopRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class ShutdownRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out ShutdownRequest result, out int bytesRead)
    {
        result = new ShutdownRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out ShutdownRequest result, out int bytesRead)
    {
        result = new ShutdownRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

#nullable restore