// <auto-generated>
//   Generated by build_all.ps1 -- do not edit by hand.
// </auto-generated>

using System;

namespace Espmon
{
    public static class FirmwareBuild
    {
        public static readonly ushort VersionMajor = 4;
        public static readonly ushort VersionMinor = 0;
        public static readonly ulong Timestamp = (ulong)1777749081;
    }
}
