// <auto-generated />
// Auto-generated by buffers_gen_cs_inline.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Htcw;

namespace Espmon;

enum Command : byte
{
    CmdNone = 0,
    CmdScreen = 1,
    CmdData = 2,
    CmdMode = 3,
    CmdIdent = 4,
    CmdNop = 5,
    CmdClear = 6,
    CmdRefreshScreen = 7,
}

enum InputType : byte
{
    InputNone = 0,
    InputTouch = 1,
    InputButton = 2,
}

[InlineArray(12)]
struct InterfaceInlineByteLength12
{
    private byte _e0;
}

[InlineArray(16)]
struct InterfaceInlineByteLength16
{
    private byte _e0;
}

[InlineArray(6)]
struct InterfaceInlineByteLength6
{
    private byte _e0;
}

[InlineArray(64)]
struct InterfaceInlineByteLength64
{
    private byte _e0;
}

struct InterfaceMaxSize
{
    internal const int Value = 164;
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseValue
{
    internal const int StructMaxSize = 8;

    internal float Value;
    internal float Scaled;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 4;
            size += 4;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseValue result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 4) { bytesRead = 0; return false; }
        result.Value = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 4) { bytesRead = 0; return false; }
        result.Scaled = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 4) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), Value); offset += 4;
        if (span.Length - offset < 4) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), Scaled); offset += 4;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseValue result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseValue result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseValueEntry
{
    internal const int StructMaxSize = 16;

    internal ResponseValue Value1;
    internal ResponseValue Value2;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Value1.SizeOfStruct;
            size += Value2.SizeOfStruct;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseValueEntry result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (!ResponseValue.TryReadCore(span.Slice(offset), out result.Value1, out int _n_value1)) { bytesRead = 0; return false; }
        offset += _n_value1;
        if (!ResponseValue.TryReadCore(span.Slice(offset), out result.Value2, out int _n_value2)) { bytesRead = 0; return false; }
        offset += _n_value2;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (!Value1.TryWriteCore(span.Slice(offset), out int _n_value1)) { bytesWritten = 0; return false; }
        offset += _n_value1;
        if (!Value2.TryWriteCore(span.Slice(offset), out int _n_value2)) { bytesWritten = 0; return false; }
        offset += _n_value2;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseValueEntry result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseValueEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseData
{
    internal const int StructMaxSize = 32;

    internal ResponseValueEntry Top;
    internal ResponseValueEntry Bottom;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Top.SizeOfStruct;
            size += Bottom.SizeOfStruct;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseData result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (!ResponseValueEntry.TryReadCore(span.Slice(offset), out result.Top, out int _n_top)) { bytesRead = 0; return false; }
        offset += _n_top;
        if (!ResponseValueEntry.TryReadCore(span.Slice(offset), out result.Bottom, out int _n_bottom)) { bytesRead = 0; return false; }
        offset += _n_bottom;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (!Top.TryWriteCore(span.Slice(offset), out int _n_top)) { bytesWritten = 0; return false; }
        offset += _n_top;
        if (!Bottom.TryWriteCore(span.Slice(offset), out int _n_bottom)) { bytesWritten = 0; return false; }
        offset += _n_bottom;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseData result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseData result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseColor
{
    internal const int StructMaxSize = 4;

    internal byte A;
    internal byte R;
    internal byte G;
    internal byte B;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 1;
            size += 1;
            size += 1;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseColor result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.A = span[offset];
        offset += 1;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.R = span[offset];
        offset += 1;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.G = span[offset];
        offset += 1;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.B = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = A; offset += 1;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = R; offset += 1;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = G; offset += 1;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = B; offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseColor result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseColor result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseScreenValueEntry
{
    internal const int StructMaxSize = 17;

    internal ResponseColor Color;
    private InterfaceInlineByteLength12 _suffix;
    internal string Suffix
    {
        get => Buffers.DecodeUtf8((ReadOnlySpan<byte>)_suffix);
        set => Buffers.EncodeUtf8(value.AsSpan(), ((Span<byte>)_suffix));
    }
    [UnscopedRef] internal ReadOnlySpan<byte> GetSuffixSpan() => Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_suffix);
    internal void SetSuffix(ReadOnlySpan<char> value) => Buffers.EncodeUtf8(value, ((Span<byte>)_suffix));

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Color.SizeOfStruct;
            size += 1 + Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_suffix).Length;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreenValueEntry result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (!ResponseColor.TryReadCore(span.Slice(offset), out result.Color, out int _n_color)) { bytesRead = 0; return false; }
        offset += _n_color;
        {
            if (span.Length - offset < 1) { bytesRead = 0; return false; }
            int _l = (int)(span[offset]); offset += 1;
            if (_l > 12 || span.Length - offset < _l) { bytesRead = 0; return false; }
            span.Slice(offset, _l).CopyTo((Span<byte>)result._suffix);
            ((Span<byte>)result._suffix).Slice(_l).Clear(); offset += _l;
        }
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (!Color.TryWriteCore(span.Slice(offset), out int _n_color)) { bytesWritten = 0; return false; }
        offset += _n_color;
        {
            int _l = Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_suffix).Length;
            if (span.Length - offset < 1 + _l) { bytesWritten = 0; return false; }
            span[offset] = (byte)_l; offset += 1;
            ((ReadOnlySpan<byte>)_suffix).Slice(0, _l).CopyTo(span.Slice(offset, _l)); offset += _l;
        }
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreenValueEntry result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseScreenValueEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseScreenEntry
{
    internal const int StructMaxSize = 55;

    private InterfaceInlineByteLength16 _label;
    internal string Label
    {
        get => Buffers.DecodeUtf8((ReadOnlySpan<byte>)_label);
        set => Buffers.EncodeUtf8(value.AsSpan(), ((Span<byte>)_label));
    }
    [UnscopedRef] internal ReadOnlySpan<byte> GetLabelSpan() => Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_label);
    internal void SetLabel(ReadOnlySpan<char> value) => Buffers.EncodeUtf8(value, ((Span<byte>)_label));
    internal ResponseColor Color;
    internal ResponseScreenValueEntry Value1;
    internal ResponseScreenValueEntry Value2;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1 + Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_label).Length;
            size += Color.SizeOfStruct;
            size += Value1.SizeOfStruct;
            size += Value2.SizeOfStruct;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreenEntry result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        {
            if (span.Length - offset < 1) { bytesRead = 0; return false; }
            int _l = (int)(span[offset]); offset += 1;
            if (_l > 16 || span.Length - offset < _l) { bytesRead = 0; return false; }
            span.Slice(offset, _l).CopyTo((Span<byte>)result._label);
            ((Span<byte>)result._label).Slice(_l).Clear(); offset += _l;
        }
        if (!ResponseColor.TryReadCore(span.Slice(offset), out result.Color, out int _n_color)) { bytesRead = 0; return false; }
        offset += _n_color;
        if (!ResponseScreenValueEntry.TryReadCore(span.Slice(offset), out result.Value1, out int _n_value1)) { bytesRead = 0; return false; }
        offset += _n_value1;
        if (!ResponseScreenValueEntry.TryReadCore(span.Slice(offset), out result.Value2, out int _n_value2)) { bytesRead = 0; return false; }
        offset += _n_value2;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        {
            int _l = Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_label).Length;
            if (span.Length - offset < 1 + _l) { bytesWritten = 0; return false; }
            span[offset] = (byte)_l; offset += 1;
            ((ReadOnlySpan<byte>)_label).Slice(0, _l).CopyTo(span.Slice(offset, _l)); offset += _l;
        }
        if (!Color.TryWriteCore(span.Slice(offset), out int _n_color)) { bytesWritten = 0; return false; }
        offset += _n_color;
        if (!Value1.TryWriteCore(span.Slice(offset), out int _n_value1)) { bytesWritten = 0; return false; }
        offset += _n_value1;
        if (!Value2.TryWriteCore(span.Slice(offset), out int _n_value2)) { bytesWritten = 0; return false; }
        offset += _n_value2;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreenEntry result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseScreenEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseScreenHeader
{
    internal const int StructMaxSize = 2;

    internal sbyte Index;
    internal byte Flags;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 1;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreenHeader result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.Index = (sbyte)span[offset];
        offset += 1;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.Flags = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = (byte)Index; offset += 1;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = Flags; offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreenHeader result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseScreenHeader result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseScreen
{
    internal const int StructMaxSize = 112;

    internal ResponseScreenHeader Header;
    internal ResponseScreenEntry Top;
    internal ResponseScreenEntry Bottom;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Header.SizeOfStruct;
            size += Top.SizeOfStruct;
            size += Bottom.SizeOfStruct;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreen result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (!ResponseScreenHeader.TryReadCore(span.Slice(offset), out result.Header, out int _n_header)) { bytesRead = 0; return false; }
        offset += _n_header;
        if (!ResponseScreenEntry.TryReadCore(span.Slice(offset), out result.Top, out int _n_top)) { bytesRead = 0; return false; }
        offset += _n_top;
        if (!ResponseScreenEntry.TryReadCore(span.Slice(offset), out result.Bottom, out int _n_bottom)) { bytesRead = 0; return false; }
        offset += _n_bottom;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (!Header.TryWriteCore(span.Slice(offset), out int _n_header)) { bytesWritten = 0; return false; }
        offset += _n_header;
        if (!Top.TryWriteCore(span.Slice(offset), out int _n_top)) { bytesWritten = 0; return false; }
        offset += _n_top;
        if (!Bottom.TryWriteCore(span.Slice(offset), out int _n_bottom)) { bytesWritten = 0; return false; }
        offset += _n_bottom;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreen result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseScreen result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseClear
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseClear result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseClear result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseClear result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseIdent
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseIdent result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseIdent result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseIdent result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct ResponseRefreshScreen
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseRefreshScreen result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseRefreshScreen result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out ResponseRefreshScreen result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct RequestData
{
    internal const int StructMaxSize = 1;

    internal sbyte ScreenIndex;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out RequestData result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.ScreenIndex = (sbyte)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = (byte)ScreenIndex; offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestData result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out RequestData result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct RequestNop
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out RequestNop result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestNop result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out RequestNop result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct RequestScreen
{
    internal const int StructMaxSize = 1;

    internal sbyte ScreenIndex;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out RequestScreen result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.ScreenIndex = (sbyte)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = (byte)ScreenIndex; offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestScreen result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out RequestScreen result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct RequestSetMode
{
    internal const int StructMaxSize = 1;

    internal sbyte Mode;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out RequestSetMode result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.Mode = (sbyte)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = (byte)Mode; offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestSetMode result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out RequestSetMode result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
partial struct RequestIdent
{
    internal const int StructMaxSize = 164;

    internal ushort VersionMajor;
    internal ushort VersionMinor;
    internal ulong Build;
    internal short ID;
    private InterfaceInlineByteLength6 _mac_address;
    internal byte[] MacAddress
    {
        get => ((ReadOnlySpan<byte>)_mac_address).ToArray();
        set { if (value.Length > 6) throw new ArgumentException("value exceeds capacity", nameof(value)); value.CopyTo(((Span<byte>)_mac_address)); if (value.Length < 6) ((Span<byte>)_mac_address).Slice(value.Length).Clear(); }
    }
    [UnscopedRef] internal ReadOnlySpan<byte> GetMacAddressSpan() => ((ReadOnlySpan<byte>)_mac_address);
    private InterfaceInlineByteLength64 _display_name;
    internal string DisplayName
    {
        get => Buffers.DecodeUtf8((ReadOnlySpan<byte>)_display_name);
        set => Buffers.EncodeUtf8(value.AsSpan(), ((Span<byte>)_display_name));
    }
    [UnscopedRef] internal ReadOnlySpan<byte> GetDisplayNameSpan() => Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_display_name);
    internal void SetDisplayName(ReadOnlySpan<char> value) => Buffers.EncodeUtf8(value, ((Span<byte>)_display_name));
    private InterfaceInlineByteLength64 _slug;
    internal string Slug
    {
        get => Buffers.DecodeUtf8((ReadOnlySpan<byte>)_slug);
        set => Buffers.EncodeUtf8(value.AsSpan(), ((Span<byte>)_slug));
    }
    [UnscopedRef] internal ReadOnlySpan<byte> GetSlugSpan() => Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_slug);
    internal void SetSlug(ReadOnlySpan<char> value) => Buffers.EncodeUtf8(value, ((Span<byte>)_slug));
    internal ushort HorizontalResolution;
    internal ushort VerticalResolution;
    private byte _is_monochrome;
    internal bool IsMonochrome { get => _is_monochrome != 0; set => _is_monochrome = value ? (byte)1 : (byte)0; }
    internal float Dpi;
    internal float PixelSize;
    internal InputType InputType;

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 2;
            size += 2;
            size += 8;
            size += 2;
            size += 6 * 1;
            size += 1 + Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_display_name).Length;
            size += 1 + Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_slug).Length;
            size += 2;
            size += 2;
            size += 1;
            size += 4;
            size += 4;
            size += 1;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out RequestIdent result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        if (span.Length - offset < 2) { bytesRead = 0; return false; }
        result.VersionMajor = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 2) { bytesRead = 0; return false; }
        result.VersionMinor = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 8) { bytesRead = 0; return false; }
        result.Build = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        if (span.Length - offset < 2) { bytesRead = 0; return false; }
        result.ID = BinaryPrimitives.ReadInt16LittleEndian(span.Slice(offset));
        offset += 2;
        for (int i = 0; i < 6; i++)
        {
            if (span.Length - offset < 1) { bytesRead = 0; return false; }
            result._mac_address[i] = span[offset];
            offset += 1;
        }
        {
            if (span.Length - offset < 1) { bytesRead = 0; return false; }
            int _l = (int)(span[offset]); offset += 1;
            if (_l > 64 || span.Length - offset < _l) { bytesRead = 0; return false; }
            span.Slice(offset, _l).CopyTo((Span<byte>)result._display_name);
            ((Span<byte>)result._display_name).Slice(_l).Clear(); offset += _l;
        }
        {
            if (span.Length - offset < 1) { bytesRead = 0; return false; }
            int _l = (int)(span[offset]); offset += 1;
            if (_l > 64 || span.Length - offset < _l) { bytesRead = 0; return false; }
            span.Slice(offset, _l).CopyTo((Span<byte>)result._slug);
            ((Span<byte>)result._slug).Slice(_l).Clear(); offset += _l;
        }
        if (span.Length - offset < 2) { bytesRead = 0; return false; }
        result.HorizontalResolution = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 2) { bytesRead = 0; return false; }
        result.VerticalResolution = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result._is_monochrome = (byte)(span[offset]);
        offset += 1;
        if (span.Length - offset < 4) { bytesRead = 0; return false; }
        result.Dpi = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 4) { bytesRead = 0; return false; }
        result.PixelSize = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 1) { bytesRead = 0; return false; }
        result.InputType = (InputType)(span[offset]);
        offset += 1;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        if (span.Length - offset < 2) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), VersionMajor); offset += 2;
        if (span.Length - offset < 2) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), VersionMinor); offset += 2;
        if (span.Length - offset < 8) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), Build); offset += 8;
        if (span.Length - offset < 2) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteInt16LittleEndian(span.Slice(offset), ID); offset += 2;
        for (int i = 0; i < 6; i++)
        {
            if (span.Length - offset < 1) { bytesWritten = 0; return false; }
            span[offset] = _mac_address[i]; offset += 1;
        }
        {
            int _l = Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_display_name).Length;
            if (span.Length - offset < 1 + _l) { bytesWritten = 0; return false; }
            span[offset] = (byte)_l; offset += 1;
            ((ReadOnlySpan<byte>)_display_name).Slice(0, _l).CopyTo(span.Slice(offset, _l)); offset += _l;
        }
        {
            int _l = Buffers.TrimNullUtf8((ReadOnlySpan<byte>)_slug).Length;
            if (span.Length - offset < 1 + _l) { bytesWritten = 0; return false; }
            span[offset] = (byte)_l; offset += 1;
            ((ReadOnlySpan<byte>)_slug).Slice(0, _l).CopyTo(span.Slice(offset, _l)); offset += _l;
        }
        if (span.Length - offset < 2) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), HorizontalResolution); offset += 2;
        if (span.Length - offset < 2) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), VerticalResolution); offset += 2;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = _is_monochrome; offset += 1;
        if (span.Length - offset < 4) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), Dpi); offset += 4;
        if (span.Length - offset < 4) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), PixelSize); offset += 4;
        if (span.Length - offset < 1) { bytesWritten = 0; return false; }
        span[offset] = (byte)InputType; offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestIdent result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    internal static bool TryRead(Stream stream, out RequestIdent result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

#nullable restore