// <auto-generated />
// Auto-generated by buffers_gen_cs.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Htcw;

namespace Espmon;

enum Command : byte
{
    CmdNone = 0,
    CmdScreen = 1,
    CmdData = 2,
    CmdMode = 3,
    CmdIdent = 4,
    CmdNop = 5,
    CmdClear = 6,
    CmdRefreshScreen = 7,
}

enum InputType : byte
{
    InputNone = 0,
    InputTouch = 1,
    InputButton = 2,
}

struct InterfaceMaxSize
{
    internal const int Value = 164;
}

partial class ResponseValue
{
    internal const int StructMaxSize = 8;

    internal float Value { get; set; }
    internal float Scaled { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 4;
            size += 4;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseValue result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseValue();
        int offset = 0;
        if (span.Length - offset < 4) return false;
        result.Value = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 4) return false;
        result.Scaled = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), Value);
        offset += 4;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), Scaled);
        offset += 4;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseValue result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseValue result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseValueEntry
{
    internal const int StructMaxSize = 16;

    internal ResponseValue Value1 { get; set; }
    internal ResponseValue Value2 { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Value1 != null ? Value1.SizeOfStruct : 0;
            size += Value2 != null ? Value2.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseValueEntry result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseValueEntry();
        int offset = 0;
        if (!ResponseValue.TryRead(span.Slice(offset), out ResponseValue _Value1_val, out int _n_Value1)) return false;
        result.Value1 = _Value1_val;
        offset += _n_Value1;
        if (!ResponseValue.TryRead(span.Slice(offset), out ResponseValue _Value2_val, out int _n_Value2)) return false;
        result.Value2 = _Value2_val;
        offset += _n_Value2;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Value1 == null) return false;
        if (!Value1.TryWrite(span.Slice(offset), out int _w_Value1)) return false;
        offset += _w_Value1;
        if (Value2 == null) return false;
        if (!Value2.TryWrite(span.Slice(offset), out int _w_Value2)) return false;
        offset += _w_Value2;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseValueEntry result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseValueEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[16];
        int n = stream.Read(buf);
        if (n < 16) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[16];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseData
{
    internal const int StructMaxSize = 32;

    internal ResponseValueEntry Top { get; set; }
    internal ResponseValueEntry Bottom { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Top != null ? Top.SizeOfStruct : 0;
            size += Bottom != null ? Bottom.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseData result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseData();
        int offset = 0;
        if (!ResponseValueEntry.TryRead(span.Slice(offset), out ResponseValueEntry _Top_val, out int _n_Top)) return false;
        result.Top = _Top_val;
        offset += _n_Top;
        if (!ResponseValueEntry.TryRead(span.Slice(offset), out ResponseValueEntry _Bottom_val, out int _n_Bottom)) return false;
        result.Bottom = _Bottom_val;
        offset += _n_Bottom;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Top == null) return false;
        if (!Top.TryWrite(span.Slice(offset), out int _w_Top)) return false;
        offset += _w_Top;
        if (Bottom == null) return false;
        if (!Bottom.TryWrite(span.Slice(offset), out int _w_Bottom)) return false;
        offset += _w_Bottom;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseData result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseData result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[32];
        int n = stream.Read(buf);
        if (n < 32) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[32];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseColor
{
    internal const int StructMaxSize = 4;

    internal byte A { get; set; }
    internal byte R { get; set; }
    internal byte G { get; set; }
    internal byte B { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 1;
            size += 1;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseColor result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseColor();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.A = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.R = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.G = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.B = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = A;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = R;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = G;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = B;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseColor result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseColor result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[4];
        int n = stream.Read(buf);
        if (n < 4) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[4];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseScreenValueEntry
{
    internal const int StructMaxSize = 17;

    internal ResponseColor Color { get; set; }
    internal string Suffix { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Color != null ? Color.SizeOfStruct : 0;
            size += 1 + (string.IsNullOrEmpty(Suffix) ? 0 : Math.Min(Encoding.UTF8.GetByteCount(Suffix), 12));
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreenValueEntry result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseScreenValueEntry();
        int offset = 0;
        if (!ResponseColor.TryRead(span.Slice(offset), out ResponseColor _Color_val, out int _n_Color)) return false;
        result.Color = _Color_val;
        offset += _n_Color;
        if (span.Length - offset < 1) return false;
        {
            int _len_Suffix = (int)(span[offset]);
            offset += 1;
            if (_len_Suffix > 12 || span.Length - offset < _len_Suffix) return false;
            result.Suffix = Encoding.UTF8.GetString(span.Slice(offset, _len_Suffix));
            offset += _len_Suffix;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Color == null) return false;
        if (!Color.TryWrite(span.Slice(offset), out int _w_Color)) return false;
        offset += _w_Color;
        {
            int _byteLen_Suffix = string.IsNullOrEmpty(Suffix) ? 0 : Encoding.UTF8.GetByteCount(Suffix);
            if (_byteLen_Suffix > 12) _byteLen_Suffix = 12;
            if (span.Length - offset < 1 + _byteLen_Suffix) return false;
            span[offset] = (byte)_byteLen_Suffix;
            offset += 1;
            if (_byteLen_Suffix > 0)
            {
                Encoding.UTF8.GetBytes(Suffix.AsSpan(), span.Slice(offset, _byteLen_Suffix));
                offset += _byteLen_Suffix;
            }
        }
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreenValueEntry result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseScreenValueEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[17];
        int n = stream.Read(buf);
        if (n < 17) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[17];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseScreenEntry
{
    internal const int StructMaxSize = 55;

    internal string Label { get; set; }
    internal ResponseColor Color { get; set; }
    internal ResponseScreenValueEntry Value1 { get; set; }
    internal ResponseScreenValueEntry Value2 { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1 + (string.IsNullOrEmpty(Label) ? 0 : Math.Min(Encoding.UTF8.GetByteCount(Label), 16));
            size += Color != null ? Color.SizeOfStruct : 0;
            size += Value1 != null ? Value1.SizeOfStruct : 0;
            size += Value2 != null ? Value2.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreenEntry result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseScreenEntry();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        {
            int _len_Label = (int)(span[offset]);
            offset += 1;
            if (_len_Label > 16 || span.Length - offset < _len_Label) return false;
            result.Label = Encoding.UTF8.GetString(span.Slice(offset, _len_Label));
            offset += _len_Label;
        }
        if (!ResponseColor.TryRead(span.Slice(offset), out ResponseColor _Color_val, out int _n_Color)) return false;
        result.Color = _Color_val;
        offset += _n_Color;
        if (!ResponseScreenValueEntry.TryRead(span.Slice(offset), out ResponseScreenValueEntry _Value1_val, out int _n_Value1)) return false;
        result.Value1 = _Value1_val;
        offset += _n_Value1;
        if (!ResponseScreenValueEntry.TryRead(span.Slice(offset), out ResponseScreenValueEntry _Value2_val, out int _n_Value2)) return false;
        result.Value2 = _Value2_val;
        offset += _n_Value2;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _byteLen_Label = string.IsNullOrEmpty(Label) ? 0 : Encoding.UTF8.GetByteCount(Label);
            if (_byteLen_Label > 16) _byteLen_Label = 16;
            if (span.Length - offset < 1 + _byteLen_Label) return false;
            span[offset] = (byte)_byteLen_Label;
            offset += 1;
            if (_byteLen_Label > 0)
            {
                Encoding.UTF8.GetBytes(Label.AsSpan(), span.Slice(offset, _byteLen_Label));
                offset += _byteLen_Label;
            }
        }
        if (Color == null) return false;
        if (!Color.TryWrite(span.Slice(offset), out int _w_Color)) return false;
        offset += _w_Color;
        if (Value1 == null) return false;
        if (!Value1.TryWrite(span.Slice(offset), out int _w_Value1)) return false;
        offset += _w_Value1;
        if (Value2 == null) return false;
        if (!Value2.TryWrite(span.Slice(offset), out int _w_Value2)) return false;
        offset += _w_Value2;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreenEntry result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseScreenEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[55];
        int n = stream.Read(buf);
        if (n < 55) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[55];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseScreenHeader
{
    internal const int StructMaxSize = 2;

    internal sbyte Index { get; set; }
    internal byte Flags { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreenHeader result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseScreenHeader();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.Index = (sbyte)span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Flags = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)Index;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = Flags;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreenHeader result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseScreenHeader result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[2];
        int n = stream.Read(buf);
        if (n < 2) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[2];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseScreen
{
    internal const int StructMaxSize = 112;

    internal ResponseScreenHeader Header { get; set; }
    internal ResponseScreenEntry Top { get; set; }
    internal ResponseScreenEntry Bottom { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Header != null ? Header.SizeOfStruct : 0;
            size += Top != null ? Top.SizeOfStruct : 0;
            size += Bottom != null ? Bottom.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ResponseScreen result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ResponseScreen();
        int offset = 0;
        if (!ResponseScreenHeader.TryRead(span.Slice(offset), out ResponseScreenHeader _Header_val, out int _n_Header)) return false;
        result.Header = _Header_val;
        offset += _n_Header;
        if (!ResponseScreenEntry.TryRead(span.Slice(offset), out ResponseScreenEntry _Top_val, out int _n_Top)) return false;
        result.Top = _Top_val;
        offset += _n_Top;
        if (!ResponseScreenEntry.TryRead(span.Slice(offset), out ResponseScreenEntry _Bottom_val, out int _n_Bottom)) return false;
        result.Bottom = _Bottom_val;
        offset += _n_Bottom;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Header == null) return false;
        if (!Header.TryWrite(span.Slice(offset), out int _w_Header)) return false;
        offset += _w_Header;
        if (Top == null) return false;
        if (!Top.TryWrite(span.Slice(offset), out int _w_Top)) return false;
        offset += _w_Top;
        if (Bottom == null) return false;
        if (!Bottom.TryWrite(span.Slice(offset), out int _w_Bottom)) return false;
        offset += _w_Bottom;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseScreen result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out ResponseScreen result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[112];
        int n = stream.Read(buf);
        if (n < 112) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[112];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class ResponseClear
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseClear result, out int bytesRead)
    {
        result = new ResponseClear();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out ResponseClear result, out int bytesRead)
    {
        result = new ResponseClear();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class ResponseIdent
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseIdent result, out int bytesRead)
    {
        result = new ResponseIdent();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out ResponseIdent result, out int bytesRead)
    {
        result = new ResponseIdent();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class ResponseRefreshScreen
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out ResponseRefreshScreen result, out int bytesRead)
    {
        result = new ResponseRefreshScreen();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out ResponseRefreshScreen result, out int bytesRead)
    {
        result = new ResponseRefreshScreen();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class RequestData
{
    internal const int StructMaxSize = 1;

    internal sbyte ScreenIndex { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out RequestData result, out int bytesRead)
    {
        bytesRead = 0;
        result = new RequestData();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.ScreenIndex = (sbyte)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)ScreenIndex;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestData result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out RequestData result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[1];
        int n = stream.Read(buf);
        if (n < 1) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[1];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class RequestNop
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestNop result, out int bytesRead)
    {
        result = new RequestNop();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out RequestNop result, out int bytesRead)
    {
        result = new RequestNop();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class RequestScreen
{
    internal const int StructMaxSize = 1;

    internal sbyte ScreenIndex { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out RequestScreen result, out int bytesRead)
    {
        bytesRead = 0;
        result = new RequestScreen();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.ScreenIndex = (sbyte)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)ScreenIndex;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestScreen result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out RequestScreen result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[1];
        int n = stream.Read(buf);
        if (n < 1) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[1];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class RequestSetMode
{
    internal const int StructMaxSize = 1;

    internal sbyte Mode { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out RequestSetMode result, out int bytesRead)
    {
        bytesRead = 0;
        result = new RequestSetMode();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.Mode = (sbyte)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)Mode;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestSetMode result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out RequestSetMode result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[1];
        int n = stream.Read(buf);
        if (n < 1) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[1];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class RequestIdent
{
    internal const int StructMaxSize = 164;

    internal ushort VersionMajor { get; set; }
    internal ushort VersionMinor { get; set; }
    internal ulong Build { get; set; }
    internal short ID { get; set; }
    internal byte[] MacAddress { get; set; }
    internal string DisplayName { get; set; }
    internal string Slug { get; set; }
    internal ushort HorizontalResolution { get; set; }
    internal ushort VerticalResolution { get; set; }
    internal bool IsMonochrome { get; set; }
    internal float Dpi { get; set; }
    internal float PixelSize { get; set; }
    internal InputType InputType { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 2;
            size += 2;
            size += 8;
            size += 2;
            size += 6 * 1;
            size += 1 + (string.IsNullOrEmpty(DisplayName) ? 0 : Math.Min(Encoding.UTF8.GetByteCount(DisplayName), 64));
            size += 1 + (string.IsNullOrEmpty(Slug) ? 0 : Math.Min(Encoding.UTF8.GetByteCount(Slug), 64));
            size += 2;
            size += 2;
            size += 1;
            size += 4;
            size += 4;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out RequestIdent result, out int bytesRead)
    {
        bytesRead = 0;
        result = new RequestIdent();
        int offset = 0;
        if (span.Length - offset < 2) return false;
        result.VersionMajor = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 2) return false;
        result.VersionMinor = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 8) return false;
        result.Build = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        if (span.Length - offset < 2) return false;
        result.ID = BinaryPrimitives.ReadInt16LittleEndian(span.Slice(offset));
        offset += 2;
        {
            var _arr_MacAddress = new byte[6];
            for (int i = 0; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                _arr_MacAddress[i] = span[offset];
                offset += 1;
            }
            result.MacAddress = _arr_MacAddress;
        }
        if (span.Length - offset < 1) return false;
        {
            int _len_DisplayName = (int)(span[offset]);
            offset += 1;
            if (_len_DisplayName > 64 || span.Length - offset < _len_DisplayName) return false;
            result.DisplayName = Encoding.UTF8.GetString(span.Slice(offset, _len_DisplayName));
            offset += _len_DisplayName;
        }
        if (span.Length - offset < 1) return false;
        {
            int _len_Slug = (int)(span[offset]);
            offset += 1;
            if (_len_Slug > 64 || span.Length - offset < _len_Slug) return false;
            result.Slug = Encoding.UTF8.GetString(span.Slice(offset, _len_Slug));
            offset += _len_Slug;
        }
        if (span.Length - offset < 2) return false;
        result.HorizontalResolution = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 2) return false;
        result.VerticalResolution = BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset));
        offset += 2;
        if (span.Length - offset < 1) return false;
        result.IsMonochrome = span[offset] != 0;
        offset += 1;
        if (span.Length - offset < 4) return false;
        result.Dpi = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 4) return false;
        result.PixelSize = BinaryPrimitives.ReadSingleLittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 1) return false;
        result.InputType = (InputType)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 2) return false;
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), VersionMajor);
        offset += 2;
        if (span.Length - offset < 2) return false;
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), VersionMinor);
        offset += 2;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), Build);
        offset += 8;
        if (span.Length - offset < 2) return false;
        BinaryPrimitives.WriteInt16LittleEndian(span.Slice(offset), ID);
        offset += 2;
        {
            int _count_MacAddress = MacAddress != null ? Math.Min(MacAddress.Length, 6) : 0;
            for (int i = 0; i < _count_MacAddress; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = MacAddress[i];
                offset += 1;
            }
            for (int i = _count_MacAddress; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = (byte)0;
                offset += 1;
            }
        }
        {
            int _byteLen_DisplayName = string.IsNullOrEmpty(DisplayName) ? 0 : Encoding.UTF8.GetByteCount(DisplayName);
            if (_byteLen_DisplayName > 64) _byteLen_DisplayName = 64;
            if (span.Length - offset < 1 + _byteLen_DisplayName) return false;
            span[offset] = (byte)_byteLen_DisplayName;
            offset += 1;
            if (_byteLen_DisplayName > 0)
            {
                Encoding.UTF8.GetBytes(DisplayName.AsSpan(), span.Slice(offset, _byteLen_DisplayName));
                offset += _byteLen_DisplayName;
            }
        }
        {
            int _byteLen_Slug = string.IsNullOrEmpty(Slug) ? 0 : Encoding.UTF8.GetByteCount(Slug);
            if (_byteLen_Slug > 64) _byteLen_Slug = 64;
            if (span.Length - offset < 1 + _byteLen_Slug) return false;
            span[offset] = (byte)_byteLen_Slug;
            offset += 1;
            if (_byteLen_Slug > 0)
            {
                Encoding.UTF8.GetBytes(Slug.AsSpan(), span.Slice(offset, _byteLen_Slug));
                offset += _byteLen_Slug;
            }
        }
        if (span.Length - offset < 2) return false;
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), HorizontalResolution);
        offset += 2;
        if (span.Length - offset < 2) return false;
        BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), VerticalResolution);
        offset += 2;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)(IsMonochrome ? 1 : 0);
        offset += 1;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), Dpi);
        offset += 4;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteSingleLittleEndian(span.Slice(offset), PixelSize);
        offset += 4;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)InputType;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out RequestIdent result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out RequestIdent result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[164];
        int n = stream.Read(buf);
        if (n < 164) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[164];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

#nullable restore