// <auto-generated>
//   Generated by build_all.ps1 -- do not edit by hand.
// </auto-generated>
#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
#define FIRMWARE_BOARD_ID 5
#define FIRMWARE_DISPLAY_NAME "Lilygo TTGO T1 Display"
#define FIRMWARE_SLUG "ttgo-t1"
#define LCD_INCHES ((float)1.14)
#endif
