// Auto-generated by buffers_gen_cs_inline.py - do not edit manually.
// Shared support types for wire buffer reading/writing.
#nullable disable
using System;
using System.Text;

namespace Htcw;

internal static class BuffersStatus
{
    public const int Success  =  0;
    public const int Eof      = -1;
    public const int ErrorEof = -2;
}

internal static class Buffers
{
    /// <summary>Bytes up to (not including) the first null byte.</summary>
    internal static ReadOnlySpan<byte> TrimNullUtf8(ReadOnlySpan<byte> span)
    {
        int i = span.IndexOf((byte)0);
        return i < 0 ? span : span.Slice(0, i);
    }

    /// <summary>Chars up to (not including) the first null char.</summary>
    internal static ReadOnlySpan<char> TrimNullUtf16(ReadOnlySpan<char> span)
    {
        int i = span.IndexOf('\0');
        return i < 0 ? span : span.Slice(0, i);
    }

    internal static string DecodeUtf8(ReadOnlySpan<byte> span)
        => Encoding.UTF8.GetString(TrimNullUtf8(span));

    /// <summary>Encode chars as UTF-8 into a fixed span, zero-padded, truncating
    /// only on a whole code-point boundary.</summary>
    internal static void EncodeUtf8(ReadOnlySpan<char> value, Span<byte> dest)
    {
        dest.Clear();
        if (value.IsEmpty) return;
        var encoder = Encoding.UTF8.GetEncoder();
        encoder.Convert(value, dest, flush: true,
            out int charsUsed, out int bytesUsed, out bool completed);
    }

    internal static bool[] ToBoolArray(ReadOnlySpan<byte> span)
    {
        var r = new bool[span.Length];
        for (int i = 0; i < span.Length; i++) r[i] = span[i] != 0;
        return r;
    }

    // fixed-length variant: copy into dest span, zero-fill remainder
    internal static void FromBoolArray(bool[] value, Span<byte> dest, int cap)
    {
        int n = value == null ? 0 : Math.Min(value.Length, cap);
        if (value != null && value.Length > cap)
            throw new ArgumentException("value exceeds capacity", nameof(value));
        for (int i = 0; i < n; i++) dest[i] = value[i] ? (byte)1 : (byte)0;
        for (int i = n; i < cap; i++) dest[i] = 0;
    }

    // length-prefixed variant: copy into dest span, report count
    internal static void FromBoolArray(bool[] value, Span<byte> dest, out int count)
    {
        int n = value == null ? 0 : value.Length;
        if (n > dest.Length)
            throw new ArgumentException("value exceeds capacity", nameof(value));
        for (int i = 0; i < n; i++) dest[i] = value[i] ? (byte)1 : (byte)0;
        count = n;
    }
}
#nullable restore
