// <auto-generated />
// Auto-generated by buffers_gen_cs.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Htcw;

namespace Espmon.Service;

public enum ServiceCommand : byte
{
    Initialize = 1,
    StartService = 2,
    StopService = 3,
}

public struct InterfaceMaxSize
{
    public const int Value = 2050;
}

public partial class ErrorInfo
{
    public const int StructMaxSize = 518;

    public int Code { get; set; }
    public string Message { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 4;
            size += 2 + (string.IsNullOrEmpty(Message) ? 0 : Math.Min(Message.Length, 256) * 2);
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ErrorInfo result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ErrorInfo();
        int offset = 0;
        if (span.Length - offset < 4) return false;
        result.Code = BinaryPrimitives.ReadInt32LittleEndian(span.Slice(offset));
        offset += 4;
        if (span.Length - offset < 2) return false;
        {
            int _len_Message = (int)(BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset)));
            offset += 2;
            int _byteLen_Message = _len_Message * 2;
            if (_len_Message > 256 || span.Length - offset < _byteLen_Message) return false;
            result.Message = Encoding.Unicode.GetString(span.Slice(offset, _byteLen_Message));
            offset += _byteLen_Message;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteInt32LittleEndian(span.Slice(offset), Code);
        offset += 4;
        {
            int _charLen_Message = string.IsNullOrEmpty(Message) ? 0 : Math.Min(Message.Length, 256);
            int _byteLen_Message = _charLen_Message * 2;
            if (span.Length - offset < 2 + _byteLen_Message) return false;
            BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), (ushort)_charLen_Message);
            offset += 2;
            if (_byteLen_Message > 0)
            {
                Encoding.Unicode.GetBytes(Message.AsSpan(0, _charLen_Message), span.Slice(offset, _byteLen_Message));
                offset += _byteLen_Message;
            }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ErrorInfo result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out ErrorInfo result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[518];
        int n = stream.Read(buf);
        if (n < 518) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[518];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class InitializeRequest
{
    public const int StructMaxSize = 2050;

    public string Path { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 2 + (string.IsNullOrEmpty(Path) ? 0 : Math.Min(Path.Length, 1024) * 2);
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out InitializeRequest result, out int bytesRead)
    {
        bytesRead = 0;
        result = new InitializeRequest();
        int offset = 0;
        if (span.Length - offset < 2) return false;
        {
            int _len_Path = (int)(BinaryPrimitives.ReadUInt16LittleEndian(span.Slice(offset)));
            offset += 2;
            int _byteLen_Path = _len_Path * 2;
            if (_len_Path > 1024 || span.Length - offset < _byteLen_Path) return false;
            result.Path = Encoding.Unicode.GetString(span.Slice(offset, _byteLen_Path));
            offset += _byteLen_Path;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _charLen_Path = string.IsNullOrEmpty(Path) ? 0 : Math.Min(Path.Length, 1024);
            int _byteLen_Path = _charLen_Path * 2;
            if (span.Length - offset < 2 + _byteLen_Path) return false;
            BinaryPrimitives.WriteUInt16LittleEndian(span.Slice(offset), (ushort)_charLen_Path);
            offset += 2;
            if (_byteLen_Path > 0)
            {
                Encoding.Unicode.GetBytes(Path.AsSpan(0, _charLen_Path), span.Slice(offset, _byteLen_Path));
                offset += _byteLen_Path;
            }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out InitializeRequest result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out InitializeRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[2050];
        int n = stream.Read(buf);
        if (n < 2050) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[2050];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class InitializeResponse
{
    public const int StructMaxSize = 518;

    public ErrorInfo Error { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Error != null ? Error.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out InitializeResponse result, out int bytesRead)
    {
        bytesRead = 0;
        result = new InitializeResponse();
        int offset = 0;
        if (!ErrorInfo.TryRead(span.Slice(offset), out ErrorInfo _Error_val, out int _n_Error)) return false;
        result.Error = _Error_val;
        offset += _n_Error;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Error == null) return false;
        if (!Error.TryWrite(span.Slice(offset), out int _w_Error)) return false;
        offset += _w_Error;
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out InitializeResponse result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out InitializeResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[518];
        int n = stream.Read(buf);
        if (n < 518) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[518];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class StartRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out StartRequest result, out int bytesRead)
    {
        result = new StartRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out StartRequest result, out int bytesRead)
    {
        result = new StartRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class StopRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out StopRequest result, out int bytesRead)
    {
        result = new StopRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out StopRequest result, out int bytesRead)
    {
        result = new StopRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class StartResponse
{
    public const int StructMaxSize = 518;

    public ErrorInfo Error { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Error != null ? Error.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out StartResponse result, out int bytesRead)
    {
        bytesRead = 0;
        result = new StartResponse();
        int offset = 0;
        if (!ErrorInfo.TryRead(span.Slice(offset), out ErrorInfo _Error_val, out int _n_Error)) return false;
        result.Error = _Error_val;
        offset += _n_Error;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Error == null) return false;
        if (!Error.TryWrite(span.Slice(offset), out int _w_Error)) return false;
        offset += _w_Error;
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out StartResponse result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out StartResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[518];
        int n = stream.Read(buf);
        if (n < 518) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[518];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class StopResponse
{
    public const int StructMaxSize = 518;

    public ErrorInfo Error { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += Error != null ? Error.SizeOfStruct : 0;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out StopResponse result, out int bytesRead)
    {
        bytesRead = 0;
        result = new StopResponse();
        int offset = 0;
        if (!ErrorInfo.TryRead(span.Slice(offset), out ErrorInfo _Error_val, out int _n_Error)) return false;
        result.Error = _Error_val;
        offset += _n_Error;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (Error == null) return false;
        if (!Error.TryWrite(span.Slice(offset), out int _w_Error)) return false;
        offset += _w_Error;
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out StopResponse result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out StopResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[518];
        int n = stream.Read(buf);
        if (n < 518) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[518];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

#nullable restore