// <auto-generated />
// Auto-generated by buffers_gen_cs.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Htcw;

namespace Espmon.Service;

public enum ServiceCommand : byte
{
    AppStart = 1,
    AppEnd = 2,
}

public struct InterfaceMaxSize
{
    public const int Value = 136196;
}

public partial class ServiceAppStartRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStartRequest result, out int bytesRead)
    {
        result = new ServiceAppStartRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out ServiceAppStartRequest result, out int bytesRead)
    {
        result = new ServiceAppStartRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class ServiceDeviceEntry
{
    public const int StructMaxSize = 133;

    public string SerialNumber { get; set; }
    public int ScreenIndex { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1 + (string.IsNullOrEmpty(SerialNumber) ? 0 : Math.Min(SerialNumber.Length, 64) * 2);
            size += 4;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceDeviceEntry result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ServiceDeviceEntry();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        {
            int _len_SerialNumber = (int)(span[offset]);
            offset += 1;
            int _byteLen_SerialNumber = _len_SerialNumber * 2;
            if (_len_SerialNumber > 64 || span.Length - offset < _byteLen_SerialNumber) return false;
            result.SerialNumber = Encoding.Unicode.GetString(span.Slice(offset, _byteLen_SerialNumber));
            offset += _byteLen_SerialNumber;
        }
        if (span.Length - offset < 4) return false;
        result.ScreenIndex = BinaryPrimitives.ReadInt32LittleEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _charLen_SerialNumber = string.IsNullOrEmpty(SerialNumber) ? 0 : Math.Min(SerialNumber.Length, 64);
            int _byteLen_SerialNumber = _charLen_SerialNumber * 2;
            if (span.Length - offset < 1 + _byteLen_SerialNumber) return false;
            span[offset] = (byte)_charLen_SerialNumber;
            offset += 1;
            if (_byteLen_SerialNumber > 0)
            {
                Encoding.Unicode.GetBytes(SerialNumber.AsSpan(0, _charLen_SerialNumber), span.Slice(offset, _byteLen_SerialNumber));
                offset += _byteLen_SerialNumber;
            }
        }
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteInt32LittleEndian(span.Slice(offset), ScreenIndex);
        offset += 4;
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceDeviceEntry result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out ServiceDeviceEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[133];
        int n = stream.Read(buf);
        if (n < 133) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[133];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class ServiceAppStartResponse
{
    public const int StructMaxSize = 136196;

    public IList<ServiceDeviceEntry> Entries { get; set; }

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            {
                size += 4;
                if (Entries != null)
                    for (int i = 0; i < Math.Min(Entries.Count, 1024); i++)
                        size += Entries[i].SizeOfStruct;
            }
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceAppStartResponse result, out int bytesRead)
    {
        bytesRead = 0;
        result = new ServiceAppStartResponse();
        int offset = 0;
        {
            if (span.Length - offset < 4) return false;
            int _count_Entries = (int)(BinaryPrimitives.ReadUInt32LittleEndian(span.Slice(offset)));
            offset += 4;
            if (_count_Entries < 0 || _count_Entries > 1024) return false;
            var _list_Entries = new List<ServiceDeviceEntry>(_count_Entries);
            for (int i = 0; i < _count_Entries; i++)
            {
                if (!ServiceDeviceEntry.TryRead(span.Slice(offset), out ServiceDeviceEntry _item_Entries, out int _n_Entries)) return false;
                _list_Entries.Add(_item_Entries);
                offset += _n_Entries;
            }
            result.Entries = _list_Entries;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _count_Entries = (Entries != null ? Entries.Count : 0);
            if (_count_Entries > 1024) return false;
            if (span.Length - offset < 4) return false;
            BinaryPrimitives.WriteUInt32LittleEndian(span.Slice(offset), (uint)_count_Entries);
            offset += 4;
            for (int i = 0; i < _count_Entries; i++)
            {
                var _item_Entries = Entries[i];
                if (_item_Entries == null) return false;
                if (!_item_Entries.TryWrite(span.Slice(offset), out int _w_Entries)) return false;
                offset += _w_Entries;
            }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStartResponse result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    public static bool TryRead(Stream stream, out ServiceAppStartResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[136196];
        int n = stream.Read(buf);
        if (n < 136196) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[136196];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

public partial class ServiceAppStopRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStopRequest result, out int bytesRead)
    {
        result = new ServiceAppStopRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out ServiceAppStopRequest result, out int bytesRead)
    {
        result = new ServiceAppStopRequest();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

public partial class ServiceAppStopResponse
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStopResponse result, out int bytesRead)
    {
        result = new ServiceAppStopResponse();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(Stream stream, out ServiceAppStopResponse result, out int bytesRead)
    {
        result = new ServiceAppStopResponse();
        bytesRead = 0;
        return true;
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

#nullable restore