// <auto-generated />
// Auto-generated by buffers_gen_cs_inline.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Htcw;

namespace Espmon.Service;

public enum ServiceCommand : byte
{
    AppStart = 1,
    AppEnd = 2,
}

[InlineArray(64)]
struct InterfaceInlineCharLength64
{
    private char _e0;
}

[InlineArray(1024)]
struct InterfaceInlineServiceDeviceEntryLength1024
{
    private ServiceDeviceEntry _e0;
}

public struct InterfaceMaxSize
{
    public const int Value = 136196;
}

[StructLayout(LayoutKind.Auto)]
public partial struct ServiceAppStartRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceAppStartRequest result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStartRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out ServiceAppStartRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct ServiceDeviceEntry
{
    public const int StructMaxSize = 133;

    private InterfaceInlineCharLength64 _SerialNumber;
    public string SerialNumber
    {
        get => new string(Buffers.TrimNullUtf16((ReadOnlySpan<char>)_SerialNumber));
        set { ReadOnlySpan<char> _v = value.AsSpan(); int _n = Math.Min(_v.Length, 64); _v.Slice(0, _n).CopyTo(((Span<char>)_SerialNumber)); if (_n < 64) ((Span<char>)_SerialNumber).Slice(_n).Clear(); }
    }
    [UnscopedRef] public ReadOnlySpan<char> GetSerialNumberSpan() => Buffers.TrimNullUtf16((ReadOnlySpan<char>)_SerialNumber);
    public int ScreenIndex;

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1 + Buffers.TrimNullUtf16((ReadOnlySpan<char>)_SerialNumber).Length * 2;
            size += 4;
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceDeviceEntry result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        {
            if (span.Length - offset < 1) { bytesRead = 0; return false; }
            int _l = (int)(span[offset]); offset += 1;
            if (_l > 64 || span.Length - offset < _l * 2) { bytesRead = 0; return false; }
            for (int i = 0; i < _l; i++) { result._SerialNumber[i] = (char)(BinaryPrimitives.ReadInt16LittleEndian(span.Slice(offset))); offset += 2; }
            ((Span<char>)result._SerialNumber).Slice(_l).Clear();
        }
        if (span.Length - offset < 4) { bytesRead = 0; return false; }
        result.ScreenIndex = BinaryPrimitives.ReadInt32LittleEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        {
            int _l = Buffers.TrimNullUtf16((ReadOnlySpan<char>)_SerialNumber).Length;
            if (span.Length - offset < 1 + _l * 2) { bytesWritten = 0; return false; }
            span[offset] = (byte)_l; offset += 1;
            for (int i = 0; i < _l; i++) { BinaryPrimitives.WriteInt16LittleEndian(span.Slice(offset), (short)((ReadOnlySpan<char>)_SerialNumber)[i]); offset += 2; }
        }
        if (span.Length - offset < 4) { bytesWritten = 0; return false; }
        BinaryPrimitives.WriteInt32LittleEndian(span.Slice(offset), ScreenIndex); offset += 4;
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceDeviceEntry result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out ServiceDeviceEntry result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct ServiceAppStartResponse
{
    public const int StructMaxSize = 136196;

    private InterfaceInlineServiceDeviceEntryLength1024 _Entries;
    private int _EntriesCount;
    public ServiceDeviceEntry[] Entries
    {
        get => ((ReadOnlySpan<ServiceDeviceEntry>)_Entries).Slice(0, _EntriesCount).ToArray();
        set { if (value.Length > 1024) throw new ArgumentException("value exceeds capacity", nameof(value)); value.CopyTo(((Span<ServiceDeviceEntry>)_Entries)); _EntriesCount = value.Length; }
    }
    [UnscopedRef] public ReadOnlySpan<ServiceDeviceEntry> GetEntriesSpan() => ((ReadOnlySpan<ServiceDeviceEntry>)_Entries).Slice(0, _EntriesCount);

    public int SizeOfStruct
    {
        get
        {
            int size = 0;
            { int _c = _EntriesCount; size += 4; for (int i = 0; i < _c; i++) size += _Entries[i].SizeOfStruct; }
            return size;
        }
    }

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceAppStartResponse result, out int bytesRead)
    {
        result = default;
        int offset = 0;
        {
            if (span.Length - offset < 4) { bytesRead = 0; return false; }
            int _c = (int)(BinaryPrimitives.ReadUInt32LittleEndian(span.Slice(offset))); offset += 4;
            if ((uint)_c > 1024) { bytesRead = 0; return false; }
            for (int i = 0; i < _c; i++)
            {
                if (!ServiceDeviceEntry.TryReadCore(span.Slice(offset), out var _it, out int _n)) { bytesRead = 0; return false; }
                result._Entries[i] = _it; offset += _n;
            }
            result._EntriesCount = _c;
        }
        bytesRead = offset;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        int offset = 0;
        {
            int _c = _EntriesCount;
            if ((uint)_c > 1024) { bytesWritten = 0; return false; }
            if (span.Length - offset < 4) { bytesWritten = 0; return false; }
            BinaryPrimitives.WriteUInt32LittleEndian(span.Slice(offset), (uint)_c); offset += 4;
            for (int i = 0; i < _c; i++)
            {
                var _it = _Entries[i];
                if (!_it.TryWriteCore(span.Slice(offset), out int _n)) { bytesWritten = 0; return false; }
                offset += _n;
            }
        }
        bytesWritten = offset;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStartResponse result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out ServiceAppStartResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct ServiceAppStopRequest
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceAppStopRequest result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStopRequest result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out ServiceAppStopRequest result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

[StructLayout(LayoutKind.Auto)]
public partial struct ServiceAppStopResponse
{
    public const int StructMaxSize = 0;

    public int SizeOfStruct => 0;

    internal static bool TryReadCore(ReadOnlySpan<byte> span, out ServiceAppStopResponse result, out int bytesRead)
    {
        result = default;
        bytesRead = 0;
        return true;
    }

    internal bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    public static bool TryRead(ReadOnlySpan<byte> span, out ServiceAppStopResponse result, out int bytesRead)
        => TryReadCore(span, out result, out bytesRead);

    public bool TryWrite(Span<byte> destination, out int bytesWritten)
        => TryWriteCore(destination, out bytesWritten);

    public static bool TryRead(Stream stream, out ServiceAppStopResponse result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        int n = stream.Read(buf);
        if (n < StructMaxSize) { result = default; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    public bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[StructMaxSize];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }
}

#nullable restore